[project]
name = "pdf-converter"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "aio-pika",
    "pytest",
    "redis>=7.1.1",
    "asyncpg>=0.31.0",
    "httpx>=0.28.1",
]
